/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2006-2010 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

PROCESS(ERR_UNKNOWN, "????")
PROCESS(ERR_WARNING, "Warning")
PROCESS(ERR_NOTE, "")

PROCESS(ERR_PP_SYNTAX_ERROR, "P0001")
PROCESS(ERR_PP_USER_ERROR, "P0002")
PROCESS(ERR_PP_EXTENSION_UNSUPPORTED, "P0003")
PROCESS(ERR_PP_NO_HIGHP, "P0004")
PROCESS(ERR_PP_VERSION_NOT_FIRST, "P0005")
/* P0006 free */
PROCESS(ERR_PP_EXTENSION_AFTER_NONPREPROCESSOR_TOKEN, "P0007")

PROCESS(ERR_LP_SYNTAX_ERROR, "L0001")
PROCESS(ERR_LP_UNDEFINED_IDENTIFIER, "L0002")
PROCESS(ERR_LP_KEYWORD_RESERVED, "L0003")
PROCESS(ERR_LP_ILLEGAL_IDENTIFIER_NAME, "L0004")

PROCESS(ERR_SEM_TYPE_MISMATCH, "S0001")
PROCESS(ERR_SEM_ARRAY_PARAMETER_INTEGER, "S0002")
PROCESS(ERR_SEM_IF_PARAMETER_BOOL, "S0003")
PROCESS(ERR_SEM_OPERATOR_UNSUPPORTED, "S0004")
PROCESS(ERR_SEM_TERNARY_PARAMETER_BOOL, "S0005")
PROCESS(ERR_SEM_TERNARY_TYPE_MISMATCH, "S0006")
PROCESS(ERR_SEM_CONSTRUCTOR_WRONG_ARGS, "S0007")
PROCESS(ERR_SEM_CONSTRUCTOR_ARG_UNUSED, "S0008")
PROCESS(ERR_SEM_CONSTRUCTOR_TOO_FEW_ARGS, "S0009")
PROCESS(ERR_SEM_CONSTRUCTOR_MATRIX_FROM_MATRIX, "S0010")
PROCESS(ERR_SEM_CONSTRUCTOR_ARGS_WRONG_ORDER, "S0011")
PROCESS(ERR_SEM_EXPRESSION_CONSTANT, "S0012")
PROCESS(ERR_SEM_INITIALIZER_CONSTANT, "S0013")
PROCESS(ERR_SEM_INITIALIZER_NO_STORAGE_QUALIFIER, "S0014")
PROCESS(ERR_SEM_EXPRESSION_INTEGRAL_CONSTANT, "S0015")
PROCESS(ERR_SEM_CONST_INDEX_UNSIZED_ARRAY, "S0016")
PROCESS(ERR_SEM_ARRAY_SIZE_GREATER_ZERO, "S0017")
PROCESS(ERR_SEM_ARRAY_SIZE_UNDECLARED, "S0018")
PROCESS(ERR_SEM_ARRAY_INDEX_NONCONST_NO_SIZE, "S0019")
PROCESS(ERR_SEM_ARRAY_INDEX_TOO_BIG, "S0020")
PROCESS(ERR_SEM_ARRAY_INDEX_NEGATIVE, "S0021")
PROCESS(ERR_SEM_VARIABLE_REDEFINITION, "S0022")
PROCESS(ERR_SEM_FUNCTION_REDEFINITION, "S0023")
PROCESS(ERR_SEM_NAME_REDEFINITION, "S0024")
PROCESS(ERR_SEM_FIELD_SELECTORS_SAME_SET, "S0025")
PROCESS(ERR_SEM_ILLEGAL_FIELD_SELECTOR, "S0026")
PROCESS(ERR_SEM_ASSIGNMENT_NOT_LVALUE, "S0027")
PROCESS(ERR_SEM_PRECISION_NOT_INT_FLOAT, "S0028")
PROCESS(ERR_SEM_MAIN_SIGNATURE_MISMATCH, "S0029")
PROCESS(ERR_SEM_VERTEX_SHADER_NO_POSITION, "S0030")
PROCESS(ERR_SEM_CONST_VARIABLE_NO_INITIALIZER, "S0031")
PROCESS(ERR_SEM_FLOAT_INT_NO_DEFAULT_PRECISION, "S0032")
PROCESS(ERR_SEM_EXPRESSION_NO_DEFAULT_PRECISION, "S0033")
PROCESS(ERR_SEM_INVARIANT_ONLY_OUTPUT_VARIABLES, "S0034")
PROCESS(ERR_SEM_INVARIANT_LOCAL_SCOPE, "S0035")
/* S0036 free */
PROCESS(ERR_SEM_LVALUE_SWIZZLE_DUPLICATE_COMPONENTS, "S0037")
PROCESS(ERR_SEM_FUNCTION_DOES_NOT_RETURN_VALUE, "S0038")
PROCESS(ERR_SEM_VOID_FUNCTION_RETURNS_VALUE, "S0039")
PROCESS(ERR_SEM_FUNCTION_MISSING_SOME_RETURNS, "S0040")
PROCESS(ERR_SEM_RETURN_TYPE_ARRAY, "S0041")
PROCESS(ERR_SEM_RETURN_TYPE_MISMATCH, "S0042")
PROCESS(ERR_SEM_PARAMETER_QUALIFIER_MISMATCH, "S0043")
PROCESS(ERR_SEM_ATTRIBUTE_OUTSIDE_VERTEX_SHADER, "S0044")
PROCESS(ERR_SEM_VARYING_INSIDE_FUNCTION, "S0045")
PROCESS(ERR_SEM_UNIFORM_INSIDE_FUNCTION, "S0046")
/* S0047 and S0048 are the same as 46 and 47, skipping */
PROCESS(ERR_SEM_GL_FRAGDATA_GL_POSITION_MIX, "S0047")
/* S0048 free */
PROCESS(ERR_SEM_ILLEGAL_DATA_TYPE_FOR_ATTRIBUTE, "S0049")
PROCESS(ERR_SEM_ATTRIBUTE_INITIALIZER, "S0050")
PROCESS(ERR_SEM_VARYING_INITIALIZER, "S0051")
PROCESS(ERR_SEM_UNIFORM_INITIALIZER, "S0052")

PROCESS(ERR_LINK_GLOBAL_TYPE_MISMATCH, "L0001")
PROCESS(ERR_LINK_GLOBAL_INITIALIZER_MISMATCH, "L0002")
PROCESS(ERR_LINK_GLOBAL_PRECISION_MISMATCH, "L0003")
PROCESS(ERR_LINK_TOO_MANY_ATTRIBUTES, "L0004")
PROCESS(ERR_LINK_TOO_MANY_UNIFORMS, "L0005")
PROCESS(ERR_LINK_TOO_MANY_VARYINGS, "L0006")
PROCESS(ERR_LINK_FRAGMENT_SHADER_UNDECLARED_VARYING, "L0007")
PROCESS(ERR_LINK_VARYING_TYPE_MISMATCH, "L0008")
PROCESS(ERR_LINK_NO_ENTRY_POINT, "L0009")

PROCESS(ERR_OUT_OF_MEMORY, "F0001")
PROCESS(ERR_INTERNAL_COMPILER_ERROR, "F0002")
PROCESS(ERR_RESOURCES_EXHAUSTED, "F0003")
PROCESS(ERR_UNSAFE_CODE, "F0004")

/* Error codes missing from spec */
PROCESS(ERR_PP_VERSION_UNSUPPORTED, "P0003")
PROCESS(ERR_SEM_ATTRIBUTE_INSIDE_FUNCTION, "L0001")
PROCESS(ERR_SEM_ILLEGAL_DATA_TYPE_FOR_VARYING, "L0001")

PROCESS(ERR_SEM_NONTYPE_USED_AS_TYPE, "S0001")
PROCESS(ERR_SEM_TYPE_USED_AS_NONTYPE, "S0001")

PROCESS(ERR_SEM_INVARIANT_DECLARED_AFTER_USE, "L0001")

PROCESS(ERR_SEM_RECURSION_FOUND, "S0053")
PROCESS(ERR_SEM_DISCARD_IN_VERTEX_SHADER, "S0054")
PROCESS(ERR_SEM_ILLEGAL_SAMPLER_DECLARATION, "S0055")
PROCESS(ERR_SEM_ILLEGAL_DECLARATION, "S0056")
PROCESS(ERR_SEM_ILLEGAL_QUALIFIER_FOR_RETURN_TYPE, "S0057")
PROCESS(ERR_SEM_FUNCTION_DIFF_REDECL, "S0058")
PROCESS(ERR_SEM_FUNCTION_INSIDE_FUNCTION, "S0059")

PROCESS(NOTE_MESSAGE, "M0001")
