/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2007-2010, 2012 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif

#include "gles_helpers.h"

const char *get_glenum_name(GLenum e)
{
	switch (e)
	{
#define ENTRY(e) case e: return #e;
		ENTRY(GL_NO_ERROR)
		ENTRY(GL_OUT_OF_MEMORY)
		ENTRY(GL_INVALID_ENUM)
		ENTRY(GL_INVALID_OPERATION)
		ENTRY(GL_INVALID_VALUE)
		ENTRY(GL_INVALID_FRAMEBUFFER_OPERATION)
		ENTRY(GL_NEAREST)
		ENTRY(GL_LINEAR)
		ENTRY(GL_NEAREST_MIPMAP_NEAREST)
		ENTRY(GL_LINEAR_MIPMAP_NEAREST)
		ENTRY(GL_LINEAR_MIPMAP_LINEAR)
		ENTRY(GL_NEAREST_MIPMAP_LINEAR)
		ENTRY(GL_REPEAT)
		ENTRY(GL_CLAMP_TO_EDGE)
		ENTRY(GL_CW)
		ENTRY(GL_CCW)
		ENTRY(GL_BYTE)
		ENTRY(GL_UNSIGNED_BYTE)
		ENTRY(GL_SHORT)
		ENTRY(GL_UNSIGNED_SHORT)
		ENTRY(GL_INT)
		ENTRY(GL_UNSIGNED_INT)
		ENTRY(GL_FLOAT)
		ENTRY(GL_UNSIGNED_SHORT_4_4_4_4)
		ENTRY(GL_UNSIGNED_SHORT_5_5_5_1)
		ENTRY(GL_UNSIGNED_SHORT_5_6_5)
		ENTRY(GL_RGB)
		ENTRY(GL_RGBA)
		ENTRY(GL_RGBA4)
		ENTRY(GL_RGB5_A1)
		ENTRY(GL_RGB565)
		ENTRY(GL_DEPTH_COMPONENT)
		ENTRY(GL_DEPTH_COMPONENT16)
		ENTRY(GL_STENCIL_INDEX8)

		ENTRY(GL_FRAMEBUFFER_COMPLETE)
		ENTRY(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT)
		ENTRY(GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS)
		ENTRY(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT)
		ENTRY(GL_FRAMEBUFFER_UNSUPPORTED)

/* Extension GLenums */
		ENTRY(GL_RGB8_OES)
		ENTRY(GL_RGBA8_OES)
		ENTRY(GL_DEPTH_COMPONENT24_OES)
		ENTRY(GL_DEPTH_COMPONENT32_OES)
		ENTRY(GL_STENCIL_INDEX1_OES)
		ENTRY(GL_STENCIL_INDEX4_OES)
		ENTRY(GL_DEPTH24_STENCIL8_OES)
		ENTRY(GL_DEPTH_STENCIL_OES)
		ENTRY(GL_UNSIGNED_INT_24_8_OES)

#undef  ENTRY
	}
	return "unknown enum";
}
