/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2008-2011 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

#include "gles_entrypoints.h"

#ifdef MALI_BUILD_ANDROID_MONOLITHIC

MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v2( glAlphaFunc ,  GLenum, func, GLclampf, ref )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glAlphaFuncx ,  GLenum, func, GLclampx, ref )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glClearColorx ,  GLclampx, red, GLclampx, green, GLclampx, blue, GLclampx, alpha )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glClearDepthx ,  GLclampx, depth )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glClientActiveTexture ,  GLenum, texture )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glClipPlanef ,  GLenum, plane, maliGLConstFloatPtr,equation )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glClipPlanex ,  GLenum, plane, maliGLConstFixedPtr,equation )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v4( glColor4f ,  GLfloat, red, GLfloat, green, GLfloat, blue, GLfloat, alpha )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glColor4ub ,  GLubyte, red, GLubyte, green, GLubyte, blue, GLubyte, alpha )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glColor4x ,  GLfixed, red, GLfixed, green, GLfixed, blue, GLfixed, alpha )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glColorPointer , GLint, size, GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glDepthRangex , GLclampx, z_near, GLclampx, z_far)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glDisableClientState ,  GLenum, cap )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v5( glDrawTexfOES  , GLfloat, x, GLfloat, y, GLfloat, z, GLfloat, width, GLfloat, height)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glDrawTexfvOES  , maliGLConstFloatPtr,coords)
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glDrawTexiOES , GLint, x, GLint, y, GLint, z, GLint, width, GLint, height)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glDrawTexivOES , maliGLConstIntPtr, coords)
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glDrawTexsOES , GLshort, x, GLshort, y, GLshort, z, GLshort, width, GLshort, height)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glDrawTexsvOES , maliGLConstShortPtr, coords)
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glDrawTexxOES , GLfixed, x, GLfixed, y, GLfixed, z, GLfixed, width, GLfixed, height)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glDrawTexxvOES , maliGLConstFixedPtr,coords)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glEnableClientState ,  GLenum, cap )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v2( glFogf ,  GLenum, pname, GLfloat, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glFogfv ,  GLenum, pname, maliGLConstFloatPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glFogx ,  GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glFogxv ,  GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v6( glFrustumf , GLfloat, l, GLfloat, r, GLfloat, b, GLfloat, t, GLfloat, n, GLfloat, f)
MALI_GL_APICALL void MALI_GL_APIENTRY_v6( glFrustumx , GLfixed, l, GLfixed, r, GLfixed, b, GLfixed, t, GLfixed, n, GLfixed, f)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGetClipPlanef , GLenum, plane, maliGLFloatPtr, equation)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGetClipPlanex ,  GLenum, plane, maliGLFixedPtr, equation)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGetFixedv , GLenum, pname, maliGLFixedPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetLightfv ,  GLenum, light, GLenum, pname, maliGLFloatPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetLightxv ,  GLenum, light, GLenum, pname, maliGLFixedPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetMaterialfv ,  GLenum, face, GLenum, pname, maliGLFloatPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetMaterialxv ,  GLenum, face, GLenum, pname, maliGLFixedPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGetPointerv ,  GLenum, pname, maliGLVoidPtrPtr, pointer )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetTexEnvfv , GLenum, target, GLenum, pname, maliGLFloatPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetTexEnviv , GLenum, target, GLenum, pname, maliGLIntPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetTexEnvxv , GLenum, target, GLenum, pname, maliGLFixedPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetTexParameterxv , GLenum, target, GLenum, pname, maliGLFixedPtr, params)
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glLightf , GLenum, light, GLenum, pname, GLfloat, param)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glLightfv , GLenum, light, GLenum, pname, maliGLConstFloatPtr,param)
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v2( glLightModelf ,  GLenum, pname, GLfloat, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glLightModelfv ,  GLenum, pname, maliGLConstFloatPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glLightModelx ,  GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glLightModelxv ,  GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glLightx , GLenum, light, GLenum, pname, GLfixed, param)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glLightxv , GLenum, light, GLenum, pname, maliGLConstFixedPtr,param)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glLineWidthx ,  GLfixed, width )
MALI_GL_APICALL void MALI_GL_APIENTRY_v0( glLoadIdentity ,  void )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glLoadMatrixf ,  maliGLConstFloatPtr,m )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glLoadMatrixx ,  maliGLConstFixedPtr,m )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glLogicOp ,  GLenum, opcode )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glMaterialf ,  GLenum, face, GLenum, pname, GLfloat, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glMaterialfv ,  GLenum, face, GLenum, pname, maliGLConstFloatPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glMaterialx ,  GLenum, face, GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glMaterialxv ,  GLenum, face, GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glMatrixMode , GLenum, mode)
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glMultiTexCoord4b ,  GLenum, target, GLbyte, s, GLbyte, t, GLbyte, r, GLbyte, q )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v5( glMultiTexCoord4f ,  GLenum, target, GLfloat, s, GLfloat, t, GLfloat, r, GLfloat, q )
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glMultiTexCoord4x ,  GLenum, target, GLfixed, s, GLfixed, t, GLfixed, r, GLfixed, q )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glMultMatrixf ,  maliGLConstFloatPtr,m )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glMultMatrixx ,  maliGLConstFixedPtr,m )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glNormal3f ,  GLfloat, nx, GLfloat, ny, GLfloat, nz )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glNormal3x ,  GLfixed, nx, GLfixed, ny, GLfixed, nz )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glNormalPointer , GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v6( glOrthof , GLfloat, l, GLfloat, r, GLfloat, b, GLfloat, t, GLfloat, n, GLfloat, f)
MALI_GL_APICALL void MALI_GL_APIENTRY_v6( glOrthox , GLfixed, l, GLfixed, r, GLfixed, b, GLfixed, t, GLfixed, n, GLfixed, f)
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v2( glPointParameterf ,  GLenum, pname, GLfloat, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glPointParameterfv ,  GLenum, pname, maliGLConstFloatPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glPointParameterx ,  GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glPointParameterxv ,  GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v1( glPointSize ,  GLfloat, size )
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glPointSizex ,  GLfixed, size )
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glPolygonOffsetx ,  GLfixed, factor, GLfixed, units )
MALI_GL_APICALL void MALI_GL_APIENTRY_v0( glPopMatrix ,  void )
MALI_GL_APICALL void MALI_GL_APIENTRY_v0( glPushMatrix ,  void )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v4( glRotatef , GLfloat, angle, GLfloat, x, GLfloat, y, GLfloat, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glRotatex , GLfixed, angle, GLfixed, x, GLfixed, y, GLfixed, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glSampleCoveragex ,  GLclampx, value, GLboolean, invert )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glScalef , GLfloat, x, GLfloat, y, GLfloat, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glScalex , GLfixed, x, GLfixed, y, GLfixed, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glShadeModel , GLenum, mode )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glTexCoordPointer , GLint, size, GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glTexEnvf ,  GLenum, target, GLenum, pname, GLfloat, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexEnvfv ,  GLenum, target, GLenum, pname, maliGLConstFloatPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexEnvi ,  GLenum, target, GLenum, pname, GLint, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexEnviv ,  GLenum, target, GLenum, pname, maliGLConstIntPtr, params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexEnvx ,  GLenum, target, GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexEnvxv ,  GLenum, target, GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexParameterx , GLenum, target, GLenum, pname, GLfixed, param )
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTexParameterxv , GLenum, target, GLenum, pname, maliGLConstFixedPtr,params )
MALI_GL_APICALL MALI_SOFTFP void MALI_GL_APIENTRY_v3( glTranslatef , GLfloat, x, GLfloat, y, GLfloat, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glTranslatex , GLfixed, x, GLfixed, y, GLfixed, z)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glVertexPointer , GLint, size, GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glCurrentPaletteMatrixOES ,  GLuint, index )
MALI_GL_APICALL void MALI_GL_APIENTRY_v0( glLoadPaletteFromModelViewMatrixOES ,  void )
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glMatrixIndexPointerOES , GLint, size, GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glWeightPointerOES , GLint, size, GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glPointSizePointerOES , GLenum, type, GLsizei, stride, maliGLConstVoidPtr, pointer)
MALI_GL_APICALL GLbitfield MALI_GL_APIENTRY_bi2( glQueryMatrixxOES , maliGLFixedPtr,  mantissa, maliGLIntPtr,  exponent)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGenFramebuffersOES , GLsizei, n, maliGLUintPtr, framebuffers)
MALI_GL_APICALL GLboolean MALI_GL_APIENTRY_b1( glIsRenderbufferOES , GLuint, renderbuffer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glBindRenderbufferOES , GLenum, target, GLuint, renderbuffer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glDeleteRenderbuffersOES , GLsizei, n, maliGLConstUintPtr, renderbuffers)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glGenRenderbuffersOES , GLsizei, n, maliGLUintPtr, renderbuffers)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glRenderbufferStorageOES , GLenum, target, GLenum, internalformat, GLsizei, width, GLsizei, height)
MALI_GL_APICALL void MALI_GL_APIENTRY_v3( glGetRenderbufferParameterivOES , GLenum, target, GLenum, pname, maliGLIntPtr, params)
MALI_GL_APICALL GLboolean MALI_GL_APIENTRY_b1( glIsFramebufferOES , GLuint, framebuffer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glBindFramebufferOES , GLenum, target, GLuint, framebuffer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v2( glDeleteFramebuffersOES , GLsizei, n, maliGLConstUintPtr, framebuffers)
MALI_GL_APICALL GLenum MALI_GL_APIENTRY_e1( glCheckFramebufferStatusOES , GLenum, target)
MALI_GL_APICALL void MALI_GL_APIENTRY_v5( glFramebufferTexture2DOES , GLenum, target, GLenum, attachment, GLenum, textarget, GLuint, texture, GLint, level)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glFramebufferRenderbufferOES , GLenum, target, GLenum, attachment, GLenum, renderbuffertarget, GLuint, renderbuffer)
MALI_GL_APICALL void MALI_GL_APIENTRY_v4( glGetFramebufferAttachmentParameterivOES , GLenum, target, GLenum, attachment, GLenum, pname, maliGLIntPtr, params)
MALI_GL_APICALL void MALI_GL_APIENTRY_v1( glGenerateMipmapOES , GLenum, target)

#endif /* MALI_BUILD_ANDROID_MONOLITHIC */
