/*
 This confidential and proprietary software may be used only as
 authorised by a licensing agreement from ARM Limited
 (C) COPYRIGHT 2010 ARM Limited
 ALL RIGHTS RESERVED
 The entire notice above must be reproduced on all authorised
 copies and copies may only be made to the extent permitted
 by a licensing agreement from ARM Limited.
*/

/*
 NOTICE
   This is an autogenerated file, do not edit
*/


char* __mali_build_info(void) { return "mali: BUILD=RELEASE ARCH=arch_011_udd PLATFORM=nxp4330 TRACE=0 THREAD= GEOM=mali_gp_geometry_common CORES=MALI400 USING_MALI400=1 TARGET_CORE_REVISION=0x0101 TOPLEVEL_REPO_URL=Linux-r3p2-01rel0 REVISION=버전관리 대상이 아닌 디렉토리 CHANGED_REVISION=Linux-r3p2-01rel0 REPO_URL=Linux-r3p2-01rel0 BUILD_DATE=2014. 02. 04. (화) 13:27:13 KST CHANGE_DATE=Linux-r3p2-01rel0 TARGET_TOOLCHAIN=arm-linux-gcc-vfp HOST_TOOLCHAIN=gcc TARGET_TOOLCHAIN_VERSION= HOST_TOOLCHAIN_VERSION=gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1)  TARGET_SYSTEM=gcc-arm-vfp-linux HOST_SYSTEM=gcc-x86_64-linux CPPFLAGS= CUSTOMER=internal VARIANT=mali400-r1p1-gles11-gles20-linux-android-rgb_is_xrgb-jellybean_mr1-drawmerge-dma_buf-no_profiling HOSTLIB=direct INSTRUMENTED=FALSE USING_MRI=FALSE MALI_TEST_API= UDD_OS=linux "; }
