#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
# (C) COPYRIGHT 2007-2011 ARM Limited
# ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#

# This file is called by the Linux build system.

# set up defaults if not defined by the user
TIMESTAMP ?= default
OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB ?= 16
USING_GPU_UTILIZATION ?= 1
PROFILING_SKIP_PP_JOBS ?= 0
PROFILING_SKIP_PP_AND_GP_JOBS ?= 0
MALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP ?= 0
MALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED ?= 0
MALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS ?= 0
MALI_UPPER_HALF_SCHEDULING ?= 1

# For customer releases the Linux Device Drivers will be provided as ARM proprietary and GPL releases:
# The ARM proprietary product will only include the license/proprietary directory
# The GPL product will only include the license/gpl directory
ifeq ($(wildcard $(src)/linux/license/gpl/*),)
    ccflags-y += -I$(src)/linux/license/proprietary
    ifeq ($(CONFIG_MALI400_PROFILING),y)
        $(error Profiling is incompatible with non-GPL license)
    endif
    ifeq ($(CONFIG_PM_RUNTIME),y)
        $(error Runtime PM is incompatible with non-GPL license)
    endif
    ifeq ($(CONFIG_DMA_SHARED_BUFFER),y)
        $(error DMA-BUF is incompatible with non-GPL license)
    endif
    $(error Linux Device integration is incompatible with non-GPL license)
else
    ccflags-y += -I$(src)/linux/license/gpl
endif

vr-y += \
	linux/vr_osk_atomics.o \
	linux/vr_osk_irq.o \
	linux/vr_osk_wq.o \
	linux/vr_osk_locks.o \
	linux/vr_osk_wait_queue.o \
	linux/vr_osk_low_level_mem.o \
	linux/vr_osk_math.o \
	linux/vr_osk_memory.o \
	linux/vr_osk_misc.o \
	linux/vr_osk_vr.o \
	linux/vr_osk_notification.o \
	linux/vr_osk_time.o \
	linux/vr_osk_timers.o

vr-y += \
	linux/vr_ukk_mem.o \
	linux/vr_ukk_gp.o \
	linux/vr_ukk_pp.o \
	linux/vr_ukk_core.o

# Source files which always are included in a build
vr-y += \
	common/vr_kernel_core.o \
	linux/vr_kernel_linux.o \
	common/vr_kernel_descriptor_mapping.o \
	common/vr_session.o \
	common/vr_device_pause_resume.o \
	common/vr_kernel_vsync.o \
	linux/vr_ukk_vsync.o \
	linux/vr_kernel_sysfs.o \
	common/vr_mmu.o \
	common/vr_mmu_page_directory.o \
	common/vr_memory.o \
	common/vr_kernel_memory_engine.o \
	common/vr_block_allocator.o \
	common/vr_kernel_mem_os.o \
	common/vr_mem_validation.o \
	common/vr_hw_core.o \
	common/vr_gp.o \
	common/vr_pp.o \
	common/vr_pp_job.o \
	common/vr_gp_job.o \
	common/vr_scheduler.o \
	common/vr_gp_scheduler.o \
	common/vr_pp_scheduler.o \
	common/vr_group.o \
	common/vr_dlbu.o \
	common/vr_broadcast.o \
	common/vr_pm.o \
	common/vr_pmu.o \
	common/vr_user_settings_db.o \
	common/vr_kernel_utilization.o \
	common/vr_l2_cache.o \
	linux/vr_osk_pm.o \
	linux/vr_pmu_power_up_down.o \
	__vrdrv_build_info.o

ifneq ($(MALI_PLATFORM_FILES),)
	vr-y += $(MALI_PLATFORM_FILES:.c=.o)
endif

vr-$(CONFIG_MALI400_PROFILING) += linux/vr_ukk_profiling.o
vr-$(CONFIG_MALI400_PROFILING) += linux/vr_osk_profiling.o

vr-$(CONFIG_MALI400_INTERNAL_PROFILING) += linux/vr_profiling_internal.o timestamp-$(TIMESTAMP)/vr_timestamp.o
ccflags-$(CONFIG_MALI400_INTERNAL_PROFILING) += -I$(src)/timestamp-$(TIMESTAMP)

vr-$(CONFIG_DMA_SHARED_BUFFER) += linux/vr_dma_buf.o
vr-$(CONFIG_SYNC) += linux/vr_sync.o linux/vr_sync_user.o

# Tell the Linux build system from which .o file to create the kernel module
obj-$(CONFIG_MALI400) := vr.o

ccflags-y += $(EXTRA_DEFINES)

# Set up our defines, which will be passed to gcc
ccflags-y += -DPROFILING_SKIP_PP_JOBS=$(PROFILING_SKIP_PP_JOBS)
ccflags-y += -DPROFILING_SKIP_PP_AND_GP_JOBS=$(PROFILING_SKIP_PP_AND_GP_JOBS)

ccflags-y += -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=$(MALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP)
ccflags-y += -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=$(MALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED)
ccflags-y += -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=$(MALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS)
ccflags-y += -DMALI_STATE_TRACKING=1
ccflags-y += -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=$(OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB)
ccflags-y += -DUSING_GPU_UTILIZATION=$(USING_GPU_UTILIZATION)

ifeq ($(MALI_UPPER_HALF_SCHEDULING),1)
	ccflags-y += -DMALI_UPPER_HALF_SCHEDULING
endif

ccflags-$(CONFIG_MALI400_UMP) += -I$(src)/../../ump/include/ump
ccflags-$(CONFIG_MALI400_DEBUG) += -DDEBUG

# Use our defines when compiling
ccflags-y += -I$(src) -I$(src)/include -I$(src)/common -I$(src)/linux -I$(src)/platform

# Get subversion revision number, fall back to only ${MALI_RELEASE_NAME} if no svn info is available
MALI_RELEASE_NAME=$(shell cat $(src)/.version 2> /dev/null)

SVN_INFO = (cd $(src); (svn info || git svn info || \
	echo -e "\nURL: $(MALI_RELEASE_NAME)\n" \
	"Last Changed Rev: $(MALI_RELEASE_NAME)\n" \
	"Last Changed Date: $(MALI_RELEASE_NAME)") 2>/dev/null)

SVN_REV := $(shell (cd $(src); echo "$(SVN_INFO)" | grep '^Revision: '| sed -e 's/^Revision: //' ) 2>/dev/null )
ifeq ($(SVN_REV),)
SVN_REV := $(MALI_RELEASE_NAME)
else
SVN_REV := $(MALI_RELEASE_NAME)-r$(SVN_REV)
endif

ccflags-y += -DSVN_REV_STRING=\"$(SVN_REV)\"

VERSION_STRINGS :=
VERSION_STRINGS += API_VERSION=$(shell cd $(src); grep "\#define _MALI_API_VERSION" $(FILES_PREFIX)include/linux/vr/vr_utgard_uk_types.h | cut -d' ' -f 3 )
VERSION_STRINGS += REPO_URL=$(shell $(SVN_INFO) | grep '^URL: ' | cut -d: -f2- | cut -b2-)
VERSION_STRINGS += REVISION=$(SVN_REV)
VERSION_STRINGS += CHANGED_REVISION=$(shell $(SVN_INFO) | grep '^Last Changed Rev: ' | cut -d: -f2- | cut -b2-)
VERSION_STRINGS += CHANGE_DATE=$(shell $(SVN_INFO) | grep '^Last Changed Date: ' | cut -d: -f2- | cut -b2-)
VERSION_STRINGS += BUILD_DATE=$(shell date)
ifdef CONFIG_MALI400_DEBUG
VERSION_STRINGS += BUILD=debug
else
VERSION_STRINGS += BUILD=release
endif
VERSION_STRINGS += TARGET_PLATFORM=$(TARGET_PLATFORM)
VERSION_STRINGS += MALI_PLATFORM=$(MALI_PLATFORM)
VERSION_STRINGS += KDIR=$(KDIR)
VERSION_STRINGS += OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=$(OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB)
VERSION_STRINGS += USING_UMP=$(CONFIG_MALI400_UMP)
VERSION_STRINGS += USING_PROFILING=$(CONFIG_MALI400_PROFILING)
VERSION_STRINGS += USING_INTERNAL_PROFILING=$(CONFIG_MALI400_INTERNAL_PROFILING)
VERSION_STRINGS += USING_GPU_UTILIZATION=$(USING_GPU_UTILIZATION)
VERSION_STRINGS += MALI_UPPER_HALF_SCHEDULING=$(MALI_UPPER_HALF_SCHEDULING)

# Create file with Mali driver configuration
$(src)/__vrdrv_build_info.c:
	@echo 'const char *__vrdrv_build_info(void) { return "vrdrv: $(VERSION_STRINGS)";}' > $(src)/__vrdrv_build_info.c
