#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
# (C) COPYRIGHT 2006-2010 ARM Limited
# ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#
# -*- mode: makefile -*- 

DEP_OBJS = $(filter %$(OBJ_EXT),\
	$(call source-to-object,$(HOST_SYSTEM),$(HOST_DEP_SRCS)) \
	$(call source-to-object,$(TARGET_SYSTEM),$(TARGET_DEP_SRCS)))
DEPS = $(patsubst %.small$(OBJ_EXT),%.d,$(patsubst %.fast$(OBJ_EXT),%.d,$(DEP_OBJS)))

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(MAKECMDGOALS),distclean)
ifneq ($(MAKECMDGOALS),check-syntax)
-include $(DEPS)
endif
endif
endif
