/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2007-2012 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

#include <base/mali_runtime.h>

#ifdef MALI_DUMP_ENABLE

	#include <base/pp/mali_pp_job.h>
	#include <mali_render_regs.h>

	const char * m200_register_names[] =
	{
		"M200_FRAME_REG_REND_LIST_ADDR",
		"M200_FRAME_REG_REND_RSW_BASE",
		"M200_FRAME_REG_REND_VERTEX_BASE",
		"M200_FRAME_REG_FEATURE_ENABLE",
		"M200_FRAME_REG_Z_CLEAR_VALUE",
		"M200_FRAME_REG_STENCIL_CLEAR_VALUE",
		"M200_FRAME_REG_ABGR_CLEAR_VALUE_0",
		"M200_FRAME_REG_ABGR_CLEAR_VALUE_1",
		"M200_FRAME_REG_ABGR_CLEAR_VALUE_2",
		"M200_FRAME_REG_ABGR_CLEAR_VALUE_3",
		"M200_FRAME_REG_BOUNDING_BOX_LEFT_RIGHT",
		"M200_FRAME_REG_BOUNDING_BOX_BOTTOM",
		"M200_FRAME_REG_FS_STACK_ADDR",
		"M200_FRAME_REG_FS_STACK_SIZE_AND_INIT_VAL",
		"M200_FRAME_REG_REND_CLIP_VERTEX_BASE",
		"M200_FRAME_REG_REND_FIRST_CLIP_VERTEX",
		"M200_FRAME_REG_ORIGIN_OFFSET_X",
		"M200_FRAME_REG_ORIGIN_OFFSET_Y",
		"M200_FRAME_REG_SUBPIXEL_SPECIFIER",
		"M200_FRAME_REG_TIEBREAK_MODE",
#if defined(USING_MALI400) || defined(USING_MALI450)
		"M400_FRAME_REG_PLIST_CONFIG",
		"M400_FRAME_REG_SCALING_CONFIG",
		"M400_FRAME_REG_TILEBUFFER_BITS",
#elif defined(USING_MALI200)
		/* There are no M200 only registers */
#else
#error "no supported mali core defined"
#endif
		"M200_WB0_REG_SOURCE_SELECT",
		"M200_WB0_REG_TARGET_ADDR",
		"M200_WB0_REG_TARGET_PIXEL_FORMAT",
		"M200_WB0_REG_TARGET_AA_FORMAT",
		"M200_WB0_REG_TARGET_LAYOUT",
		"M200_WB0_REG_TARGET_SCANLINE_LENGTH",
		"M200_WB0_REG_TARGET_FLAGS",
		"M200_WB0_REG_MRT_ENABLE",
		"M200_WB0_REG_MRT_OFFSET",
		"M200_WB0_REG_GLOBAL_TEST_ENABLE",
		"M200_WB0_REG_GLOBAL_TEST_REF_VALUE",
		"M200_WB0_REG_GLOBAL_TEST_CMP_FUNC",

		"M200_WB1_REG_SOURCE_SELECT",
		"M200_WB1_REG_TARGET_ADDR",
		"M200_WB1_REG_TARGET_PIXEL_FORMAT",
		"M200_WB1_REG_TARGET_AA_FORMAT",
		"M200_WB1_REG_TARGET_LAYOUT",
		"M200_WB1_REG_TARGET_SCANLINE_LENGTH",
		"M200_WB1_REG_TARGET_FLAGS",
		"M200_WB1_REG_MRT_ENABLE",
		"M200_WB1_REG_MRT_OFFSET",
		"M200_WB1_REG_GLOBAL_TEST_ENABLE",
		"M200_WB1_REG_GLOBAL_TEST_REF_VALUE",
		"M200_WB1_REG_GLOBAL_TEST_CMP_FUNC",

		"M200_WB2_REG_SOURCE_SELECT",
		"M200_WB2_REG_TARGET_ADDR",
		"M200_WB2_REG_TARGET_PIXEL_FORMAT",
		"M200_WB2_REG_TARGET_AA_FORMAT",
		"M200_WB2_REG_TARGET_LAYOUT",
		"M200_WB2_REG_TARGET_SCANLINE_LENGTH",
		"M200_WB2_REG_TARGET_FLAGS",
		"M200_WB2_REG_MRT_ENABLE",
		"M200_WB2_REG_MRT_OFFSET",
		"M200_WB2_REG_GLOBAL_TEST_ENABLE",
		"M200_WB2_REG_GLOBAL_TEST_REF_VALUE",
		"M200_WB2_REG_GLOBAL_TEST_CMP_FUNC"
	};

const char *mali_dump_get_register_name(u32 reg_nr)
{
	return m200_register_names[reg_nr];
}

#endif /* #ifdef MALI_DUMP_ENABLE */
